[package]
name = "pong"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.29"
wgpu = "0.19"
log = "0.4"
env_logger = "0.11"
futures = "0.3"
bytemuck = { version = "1.13", features = ["derive"] }
nalgebra = "0.32"
